using Test
using BHPtoolkit
using Printf

# ============================================================
#  BigFloat precision gate vs Wolfram Teukolsky @ 30 digits
#
#  Reference: test/wolfram_ref_hp.txt (generated by
#  scratchpad/teuk_ref_hp.wls at WorkingPrecision -> 30, fields:
#    s;l;m;a;ω; λre;λim; νre;νim; Binc; Bref; Rin(10); Rup(10) )
#
#  This is the FORWARD-LOOKING gate for the Track-A precision refactor: it runs
#  every layer at setprecision(256), prints the achieved relErr vs Wolfram@30,
#  and @test-guards each layer at the CURRENT achieved accuracy. The tolerances
#  are TIGHTENED as each phase lands (git history tracks the progress); the
#  printed table is the live precision tracker.
#
#  Status (after A2 ν, A5 _cgamma, A4 radial — all landed):
#    λ    : exact at a=0; ~1e-15 Kerr (Float64 LAPACK)            → A1 (low pri)
#    ν    : full precision (a=0); Kerr λ-limited                  ✓ A2
#    Binc : full precision (self-converges ~1e-74); the residual ~1e-16 below
#           is the Wolfram WP-30 reference's own amplitude accuracy, not a cap ✓ A5
#    Rin/Rup: full precision — see the reference-free Wronskian testset below ✓ A4
#  Note: the Wolfram@30 grid measures λ/ν well but its radial & amplitude values
#  are only ~9–16 digits at these points, so it cannot gate Rin/Binc below that.
#  The Wronskian-constancy testset is the true radial-precision metric.
# ============================================================

pb(s) = parse(BigFloat, s)
pc(re, im) = (re == "ERR" || im == "ERR") ? nothing : Complex{BigFloat}(pb(re), pb(im))
relerr(a, b) = b === nothing ? NaN : (abs(b) == 0 ? abs(a - b) : abs(a - b) / abs(b))
function nu_dist(νj, νr)
    νr === nothing && return NaN
    minimum(abs(νj - c) for c in (νr, -νr - 1, conj(νr), conj(-νr - 1)))
end

const REF_FILE = joinpath(@__DIR__, "wolfram_ref_hp.txt")

@testset "BigFloat precision gate (vs Wolfram@30, 256-bit)" begin
    setprecision(BigFloat, 256) do
        @printf("\n%-22s | %-9s %-9s %-9s %-9s %-9s\n",
                "case", "λ", "ν", "Binc", "Rin", "Rup")
        println("-"^78)
        for ln in readlines(REF_FILE)
            isempty(strip(ln)) && continue
            f = split(strip(ln), ";")
            s = parse(Int, f[1]); l = parse(Int, f[2]); m = parse(Int, f[3])
            a = pb(f[4]); om = pb(f[5])
            λr = pc(f[6], f[7]); νr = pc(f[8], f[9])
            Bincr = pc(f[10], f[11]); Brefr = pc(f[12], f[13])
            Rinr = pc(f[14], f[15]); Rupr = pc(f[16], f[17])

            ω = Complex{BigFloat}(om)
            p   = MSTParams(s, l, m, a, ω)
            amp = compute_amplitudes(s, l, m, a, ω)
            ν, fn = amp.ν, amp.fn

            eλ = relerr(p.λ, λr)
            eν = nu_dist(ν, νr)
            eB = relerr(amp.Binc, Bincr)
            rin_ok = Rinr !== nothing && abs(Rinr) > 1e-30
            rup_ok = Rupr !== nothing && abs(Rupr) > 1e-30
            eRin = rin_ok ? relerr(Rin(p, ν, fn, BigFloat(10)), Rinr) : NaN
            eRup = rup_ok ? relerr(Rup(p, ν, fn, BigFloat(10)), Rupr) : NaN
            @printf("s%-2d l%d m%d a%.1f ω%.1f | %.2e %.2e %.2e %.2e %.2e\n",
                    s, l, m, Float64(a), Float64(om), eλ, eν, eB, eRin, eRup)

            small_ω = Float64(om) ≤ 0.5
            cur_B = Float64(om) ≤ 1.2 ? 1e-10 : 1e-5   # ω=2 amplitudes still ~1e-6 (A5/A6)

            @testset "s=$s l=$l m=$m a=$(Float64(a)) ω=$(Float64(om))" begin
                # λ — exact at a=0; Float64 LAPACK ~1e-15 for Kerr (A1 → 1e-25)
                @test eλ < (a == 0 ? 1e-25 : 1e-12)

                # ν — A2 landed: adaptive monodromy + full-precision 2π
                @test eν < 1e-13

                # Binc — improved with ν; ω=2 still amplitude-floor-limited (A5/A6)
                @test eB < cur_B

                # Radial — gated only where the reference is reliable (small ω);
                # the integer/half-integer branch at ω≳1 loses accuracy in BOTH
                # codes. Tolerance loosens to A4 (radial ComplexF64 refactor).
                if small_ω && rin_ok
                    @test eRin < 1e-7
                end
                if small_ω && rup_ok
                    @test eRup < 1e-7
                end
            end
        end
    end
end

# ============================================================
#  Reference-free radial precision: Wronskian constancy at 256 bits.
#  W(r) = Δ^{s+1}(Rin·dRup − dRin·Rup) is analytically r-independent, so its
#  variation across r measures the radial accuracy directly — without a Wolfram
#  reference (whose WP-30 radial values are only ~9–16 digits at these points).
#  Pre-A4 this was ~1e-13..1e-9 (ComplexF64-capped radial layer); post-A4 it is
#  full precision (Kerr cases are λ-limited until A1).
# ============================================================
@testset "radial precision — Wronskian constancy (256-bit, reference-free)" begin
    setprecision(BigFloat, 256) do
        wron(s, l, m, a, om) = begin
            ω = Complex{BigFloat}(BigFloat(om)); ν, p = compute_nu(s, l, m, BigFloat(a), ω)
            fn = compute_fn(p, ν)
            W(r) = (BigFloat(r)^2 - 2BigFloat(r) + BigFloat(a)^2)^(s+1) *
                   (Rin(p, ν, fn, BigFloat(r)) * dRup(p, ν, fn, BigFloat(r)) -
                    dRin(p, ν, fn, BigFloat(r)) * Rup(p, ν, fn, BigFloat(r)))
            abs(W(4) - W(8)) / abs(W(4))
        end
        # a=0 (λ exact) reaches deep precision; Kerr is λ-limited (A1).
        for (s, l, m, a, om, tol) in [
                (-2, 2, 2, 0.0, 0.3, 1e-18), (-2, 2, 2, 0.0, 0.5, 1e-18),
                ( 0, 0, 0, 0.0, 0.5, 1e-18),
                (-2, 2, 2, 0.9, 0.5, 1e-13), (-2, 2, 2, 0.9, 1.0, 1e-13),
                ( 0, 2, 1, 0.7, 1.5, 1e-13)]
            @testset "s=$s l=$l m=$m a=$a ω=$om" begin
                @test wron(s, l, m, a, om) < tol
            end
        end
    end
end
