using Test
using BHPtoolkit
using Printf

# ============================================================
#  BigFloat precision gate vs Wolfram Teukolsky @ 30 digits
#
#  Reference: test/wolfram_ref_hp.txt (generated by
#  scratchpad/teuk_ref_hp.wls at WorkingPrecision -> 30, fields:
#    s;l;m;a;ω; λre;λim; νre;νim; Binc; Bref; Rin(10); Rup(10) )
#
#  This is the FORWARD-LOOKING gate for the Track-A precision refactor.
#  Each layer carries TWO assertions, both run at setprecision(256):
#    • @test        <CURRENT>  — regression guard at today's accuracy
#    • @test_broken <TARGET>   — the precision goal; flips to "Unexpectedly
#                                Pass" (then promote to @test) as each phase lands.
#
#  Current binding caps (measured 2026-06): λ already ~1e-16 (Float64 LAPACK,
#  exact at a=0); ν floored ~7e-14 by the monodromy nmax=60 truncation [A2];
#  radial layer ~1e-9 (down to ~1e-2 on the integer branch) from the ComplexF64
#  structs/caches [A4]. Note Kerr ν cannot beat λ, so A1 (λ) gates A2 for a≠0.
# ============================================================

const TARGET_ν   = 1e-22
const TARGET_B   = 1e-20
const TARGET_R   = 1e-18

pb(s) = parse(BigFloat, s)
pc(re, im) = (re == "ERR" || im == "ERR") ? nothing : Complex{BigFloat}(pb(re), pb(im))
relerr(a, b) = b === nothing ? NaN : (abs(b) == 0 ? abs(a - b) : abs(a - b) / abs(b))
function nu_dist(νj, νr)
    νr === nothing && return NaN
    minimum(abs(νj - c) for c in (νr, -νr - 1, conj(νr), conj(-νr - 1)))
end

const REF_FILE = joinpath(@__DIR__, "wolfram_ref_hp.txt")

@testset "BigFloat precision gate (vs Wolfram@30, 256-bit)" begin
    setprecision(BigFloat, 256) do
        @printf("\n%-22s | %-9s %-9s %-9s %-9s %-9s\n",
                "case", "λ", "ν", "Binc", "Rin", "Rup")
        println("-"^78)
        for ln in readlines(REF_FILE)
            isempty(strip(ln)) && continue
            f = split(strip(ln), ";")
            s = parse(Int, f[1]); l = parse(Int, f[2]); m = parse(Int, f[3])
            a = pb(f[4]); om = pb(f[5])
            λr = pc(f[6], f[7]); νr = pc(f[8], f[9])
            Bincr = pc(f[10], f[11]); Brefr = pc(f[12], f[13])
            Rinr = pc(f[14], f[15]); Rupr = pc(f[16], f[17])

            ω = Complex{BigFloat}(om)
            p   = MSTParams(s, l, m, a, ω)
            amp = compute_amplitudes(s, l, m, a, ω)
            ν, fn = amp.ν, amp.fn

            eλ = relerr(p.λ, λr)
            eν = nu_dist(ν, νr)
            eB = relerr(amp.Binc, Bincr)
            rin_ok = Rinr !== nothing && abs(Rinr) > 1e-30
            rup_ok = Rupr !== nothing && abs(Rupr) > 1e-30
            eRin = rin_ok ? relerr(Rin(p, ν, fn, BigFloat(10)), Rinr) : NaN
            eRup = rup_ok ? relerr(Rup(p, ν, fn, BigFloat(10)), Rupr) : NaN
            @printf("s%-2d l%d m%d a%.1f ω%.1f | %.2e %.2e %.2e %.2e %.2e\n",
                    s, l, m, Float64(a), Float64(om), eλ, eν, eB, eRin, eRup)

            small_ω = Float64(om) ≤ 0.5
            cur_ν = Float64(om) ≤ 1.2 ? 1e-9 : 1e-8
            cur_B = Float64(om) ≤ 1.2 ? 1e-8 : 1e-5

            @testset "s=$s l=$l m=$m a=$(Float64(a)) ω=$(Float64(om))" begin
                # λ — already high-accuracy (exact at a=0)
                @test eλ < (a == 0 ? 1e-25 : 1e-12)

                # ν — regression + precision target
                @test eν < cur_ν
                @test_broken eν < TARGET_ν

                # Binc — regression + precision target
                @test eB < cur_B
                @test_broken eB < TARGET_B

                # Radial — only assert where the reference is reliable (small ω);
                # the integer/half-integer branch at ω≳1 loses accuracy in BOTH
                # codes, so it is reported but not gated.
                if small_ω && rin_ok
                    @test eRin < 1e-7
                    @test_broken eRin < TARGET_R
                end
                if small_ω && rup_ok
                    @test eRup < 1e-7
                    @test_broken eRup < TARGET_R
                end
            end
        end
    end
end
