using Test
using BHPtoolkit

# ============================================================
#  Kerr geodesic constants of motion (src/kerr_geo_constants.jl)
#
#  Validate E, L, Q against every [case] block of geodesic_ref.txt,
#  generated by the Wolfram KerrGeodesics 0.9.0 paclet (N[.,30]).
#  (The next agent extends this file with frequencies / roots.)
# ============================================================

# Parse a Mathematica N[.,30] InputForm scalar into Float64.
#   - drop the precision annotation after a backtick `
#   - a value like "0``28.5" is exactly zero
#   - rewrite "*^" (Mathematica sci-notation) to "e"
function _parse_ref_scalar(::Type{T}, raw) where {T}
    s = strip(raw)
    bt = findfirst('`', s)
    if bt !== nothing
        head = strip(s[1:prevind(s, bt)])
        isempty(head) && return zero(T)   # "0``..." → 0
        s = head
    end
    s = replace(s, "*^" => "e")
    return parse(T, s)
end

# Read geodesic_ref.txt into a Vector of (name, Dict{String,String}) for [case] blocks.
function _read_geodesic_cases(path)
    cases = Tuple{String,Dict{String,String}}[]
    cur = nothing
    for ln in readlines(path)
        t = strip(ln)
        (isempty(t) || startswith(t, "#")) && continue
        if startswith(t, "[case]")
            name = strip(replace(t, "[case]" => ""))
            cur = Dict{String,String}()
            push!(cases, (name, cur))
        elseif startswith(t, "[")
            cur = nothing                  # leave [case] section (special-orbits/trajectory)
        elseif cur !== nothing && occursin('=', t)
            k, v = split(t, '=', limit=2)
            cur[strip(k)] = strip(v)
        end
    end
    return cases
end

@testset "Kerr geodesic constants of motion" begin
    cases = _read_geodesic_cases(joinpath(@__DIR__, "geodesic_ref.txt"))
    @test !isempty(cases)

    maxrel = 0.0
    for (name, d) in cases
        a = _parse_ref_scalar(Float64, d["a"])
        p = _parse_ref_scalar(Float64, d["p"])
        e = _parse_ref_scalar(Float64, d["e"])
        x = _parse_ref_scalar(Float64, d["x"])

        Eref = _parse_ref_scalar(Float64, d["E"])
        Lref = _parse_ref_scalar(Float64, d["L"])
        Qref = _parse_ref_scalar(Float64, d["Q"])

        E, L, Q = kerr_geo_constants_of_motion(a, p, e, x)

        @testset "$name" begin
            relE = abs(E - Eref) / max(abs(Eref), eps())
            relL = abs(L - Lref) / max(abs(Lref), eps())
            relQ = abs(Q - Qref) / max(abs(Qref), eps())
            @test relE < 1e-12
            @test relL < 1e-12
            # Q == 0 (equatorial) compared on absolute scale.
            if abs(Qref) < 1e-30
                @test abs(Q) < 1e-12
            else
                @test relQ < 1e-12
                maxrel = max(maxrel, relQ)
            end
            maxrel = max(maxrel, relE, relL)
        end
    end
    @info "Kerr geodesic constants: max relative error vs Wolfram = $maxrel"
    @test maxrel < 1e-12
end

# Type-genericity / BigFloat-safety: full agreement Float64 ↔ BigFloat,
# and the analytic relation Q = z⁻²(a²(1-E²)+L²/(1-z²)·…) stays finite.
@testset "Kerr geodesic constants — BigFloat" begin
    for (a, p, e, x) in ((big"0.8", big"11.0", big"0.3", big"0.6"),
                         (big"0.9", big"10.0", big"0.0", big"0.5"),
                         (big"0.998", big"6.0", big"0.2", big"0.7"))
        Eb, Lb, Qb = kerr_geo_constants_of_motion(a, p, e, x)
        Ef, Lf, Qf = kerr_geo_constants_of_motion(Float64(a), Float64(p),
                                                  Float64(e), Float64(x))
        @test Eb isa BigFloat
        @test abs(Float64(Eb) - Ef) / abs(Ef) < 1e-12
        @test abs(Float64(Lb) - Lf) / abs(Lf) < 1e-12
        @test abs(Float64(Qb) - Qf) / abs(Qf) < 1e-12
    end
end

# ============================================================
#  Frequencies, radial/polar roots, special orbits, trajectory
#  (src/kerr_geo_frequencies.jl, special_orbits.jl, kerr_geo_orbit.jl)
#
#  All validated against the [case], [special-orbits] and [trajectory]
#  sections of geodesic_ref.txt (Wolfram KerrGeodesics 0.9.0).
# ============================================================

# Parse a Mathematica scalar OR complex InputForm (e.g. "0. + 1.24*I").
function _parse_ref_complex(::Type{T}, raw) where {T}
    s = strip(raw)
    if occursin('I', s)
        s2 = replace(replace(s, " " => ""), "*I" => "")
        m = match(r"^([+-]?[0-9.eE]+)([+-][0-9.eE]+)$", s2)
        if m !== nothing
            return complex(parse(T, m.captures[1]), parse(T, m.captures[2]))
        else
            return complex(zero(T), parse(T, s2))   # pure imaginary
        end
    end
    return complex(_parse_ref_scalar(T, raw), zero(T))
end

# Read the [special-orbits] key=value block.
function _read_special_orbits(path)
    d = Dict{String,String}()
    insec = false
    for ln in readlines(path)
        t = strip(ln)
        (isempty(t) || startswith(t, "#")) && continue
        if startswith(t, "[special-orbits]")
            insec = true; continue
        elseif startswith(t, "[")
            insec = false; continue
        end
        if insec && occursin('=', t)
            k, v = split(t, '=', limit=2)
            d[strip(k)] = strip(v)
        end
    end
    return d
end

# Read the [trajectory] block → (a,p,e,x, Vector of (λ,t,r,θ,φ)).
function _read_trajectory(path)
    rows = Tuple{Float64,Float64,Float64,Float64,Float64}[]
    a = p = e = x = 0.0
    insec = false
    for ln in readlines(path)
        t = strip(ln)
        isempty(t) && continue
        if startswith(t, "[trajectory]")
            insec = true
            a = parse(Float64, match(r"a=([0-9.]+)", t).captures[1])
            p = parse(Float64, match(r"p=([0-9.]+)", t).captures[1])
            e = parse(Float64, match(r"e=([0-9.]+)", t).captures[1])
            x = parse(Float64, match(r"x=([0-9.]+)", t).captures[1])
            continue
        elseif startswith(t, "[")
            insec = false; continue
        end
        (!insec || startswith(t, "#")) && continue
        if occursin(':', t)
            lhs, rhs = split(t, ':', limit=2)
            λ = _parse_ref_scalar(Float64, lhs)
            vals = [_parse_ref_scalar(Float64, v) for v in split(strip(rhs))]
            push!(rows, (λ, vals[1], vals[2], vals[3], vals[4]))
        end
    end
    return a, p, e, x, rows
end

@testset "Kerr geodesic frequencies & roots" begin
    cases = _read_geodesic_cases(joinpath(@__DIR__, "geodesic_ref.txt"))
    maxrel = 0.0
    for (name, d) in cases
        a = _parse_ref_scalar(Float64, d["a"])
        p = _parse_ref_scalar(Float64, d["p"])
        e = _parse_ref_scalar(Float64, d["e"])
        x = _parse_ref_scalar(Float64, d["x"])

        @testset "$name" begin
            # --- radial & polar roots ---
            r1, r2, r3, r4 = kerr_geo_radial_roots(a, p, e, x)
            zp, zm = kerr_geo_polar_roots(a, p, e, x)
            for (got, key) in ((r1, "r1"), (r2, "r2"), (r3, "r3"), (r4, "r4"),
                               (zp, "zp"), (zm, "zm"))
                ref = _parse_ref_scalar(Float64, d[key])
                if abs(ref) < 1e-30
                    @test abs(got) < 1e-10
                else
                    rel = abs(got - ref) / abs(ref)
                    maxrel = max(maxrel, rel)
                    @test rel < 1e-10
                end
            end

            # --- Mino frequencies (Υr may be complex) ---
            f = kerr_geo_mino_frequencies(a, p, e, x)
            for (got, key) in ((f.Upsilon_t, "Upsilon_t"),
                               (f.Upsilon_theta, "Upsilon_theta"),
                               (f.Upsilon_phi, "Upsilon_phi"))
                ref = _parse_ref_scalar(Float64, d[key])
                rel = abs(real(got) - ref) / abs(ref)
                maxrel = max(maxrel, rel)
                @test rel < 1e-10
            end
            Yr_ref = _parse_ref_complex(Float64, d["Upsilon_r"])
            relYr = abs(complex(f.Upsilon_r) - Yr_ref) / abs(Yr_ref)
            maxrel = max(maxrel, relYr)
            @test relYr < 1e-10

            # --- Boyer–Lindquist frequencies (Ωr may be complex) ---
            bl = kerr_geo_boyer_lindquist_frequencies(a, p, e, x)
            for (got, key) in ((bl.Omega_theta, "Omega_theta"),
                               (bl.Omega_phi, "Omega_phi"))
                ref = _parse_ref_scalar(Float64, d[key])
                rel = abs(real(got) - ref) / abs(ref)
                maxrel = max(maxrel, rel)
                @test rel < 1e-10
            end
            Or_ref = _parse_ref_complex(Float64, d["Omega_r"])
            relOr = abs(complex(bl.Omega_r) - Or_ref) / abs(Or_ref)
            maxrel = max(maxrel, relOr)
            @test relOr < 1e-10
        end
    end
    @info "Kerr frequencies/roots: max relative error vs Wolfram = $maxrel"
    @test maxrel < 1e-10
end

@testset "Kerr special orbits" begin
    so = _read_special_orbits(joinpath(@__DIR__, "geodesic_ref.txt"))
    checks = (
        ("ISCO_a0.9_pro",            kerr_geo_isco(0.9, 1.0)),
        ("ISCO_a0.9_ret",            kerr_geo_isco(0.9, -1.0)),
        ("ISCO_schw",                kerr_geo_isco(0.0, 1.0)),
        ("Separatrix_a0.5_e0.4_eq",  kerr_geo_separatrix(0.5, 0.4, 1.0)),
        ("Separatrix_a0.9_e0_incl0.5", kerr_geo_separatrix(0.9, 0.0, 0.5)),
        ("PhotonSphere_a0.9_pro",    kerr_geo_photon_sphere_radius(0.9, 1.0)),
        ("ISSO_a0.9_polar",          kerr_geo_isso(0.9, 0.0)),
    )
    maxrel = 0.0
    for (key, got) in checks
        ref = _parse_ref_scalar(Float64, so[key])
        rel = abs(got - ref) / abs(ref)
        maxrel = max(maxrel, rel)
        @testset "$key" begin
            @test rel < 1e-10
        end
    end
    # consistency: ISSO = ISCO on the equatorial plane
    @test kerr_geo_isso(0.9, 1.0) ≈ kerr_geo_isco(0.9, 1.0)
    @info "Kerr special orbits: max relative error vs Wolfram = $maxrel"
    @test maxrel < 1e-10
end

@testset "Kerr geodesic trajectory" begin
    a, p, e, x, rows = _read_trajectory(joinpath(@__DIR__, "geodesic_ref.txt"))
    orb = KerrGeoOrbit(a, p, e, x; parametrization=:Mino, init_phases=(0, 0, 0, 0))
    @test orb.constants[1] isa Float64
    @test length(orb.radial_roots) == 4
    @test length(orb.polar_roots) == 2
    maxrel = 0.0
    for (λ, tr, rr, θr, φr) in rows
        t, r, θ, φ = orb(λ)
        for (got, ref) in ((t, tr), (r, rr), (θ, θr), (φ, φr))
            if abs(ref) < 1e-30
                @test abs(got) < 1e-10
            else
                rel = abs(got - ref) / abs(ref)
                maxrel = max(maxrel, rel)
                @test rel < 1e-9
            end
        end
    end
    @info "Kerr trajectory: max relative error vs Wolfram = $maxrel"
    @test maxrel < 1e-9
end

@testset "Kerr frequencies & orbit — BigFloat" begin
    setprecision(BigFloat, 160) do
        for (a, p, e, x) in ((big"0.8", big"11.0", big"0.3", big"0.6"),
                             (big"0.7", big"9.0", big"0.0", big"0.0"))
            fb = kerr_geo_mino_frequencies(a, p, e, x)
            ff = kerr_geo_mino_frequencies(Float64(a), Float64(p),
                                           Float64(e), Float64(x))
            @test fb.Upsilon_t isa BigFloat
            @test abs(Float64(fb.Upsilon_t) - ff.Upsilon_t) / ff.Upsilon_t < 1e-12
            @test abs(Float64(fb.Upsilon_phi) - ff.Upsilon_phi) / ff.Upsilon_phi < 1e-12
        end
        # BigFloat callable orbit reproduces the Float64 trajectory.
        orb = KerrGeoOrbit(big"0.8", big"11.0", big"0.3", big"0.6")
        t, r, θ, φ = orb(big"10.0")
        @test r isa BigFloat
        @test abs(Float64(r) - 15.119552062016766) / 15.119552062016766 < 1e-11
        @test abs(Float64(φ) - 38.721845585992924) / 38.721845585992924 < 1e-11
        # BigFloat separatrix.
        sep = kerr_geo_separatrix(big"0.5", big"0.4", big"1.0")
        @test sep isa BigFloat
        @test abs(Float64(sep) - 4.8359764630917255) / 4.8359764630917255 < 1e-11
    end

    @testset "input validation (bound-orbit domain)" begin
        # e ≥ 1 (unbound/parabolic) must error, not return garbage, at every entry.
        @test_throws ArgumentError kerr_geo_energy(0.5, 10.0, 1.0, 1.0)
        @test_throws ArgumentError kerr_geo_constants_of_motion(0.5, 10.0, 1.5, 1.0)
        @test_throws ArgumentError kerr_geo_radial_roots(0.5, 10.0, 1.0, 1.0)
        @test_throws ArgumentError kerr_geo_frequencies(0.5, 10.0, 1.0, 1.0)
        @test_throws ArgumentError KerrGeoOrbit(0.5, 10.0, 1.0, 1.0)
        # other domain violations
        @test_throws ArgumentError kerr_geo_energy(0.5, 10.0, 0.1, 1.2)   # |x| > 1
        @test_throws ArgumentError kerr_geo_energy(1.5, 10.0, 0.1, 1.0)   # |a| > 1
        # valid bound orbit still works
        @test kerr_geo_energy(0.5, 10.0, 0.3, 0.6) isa Float64
    end
end
