using Pkg
Pkg.activate("/Users/yusuke/work/BHPtoolkit.jl")

using BHPtoolkit
using Printf
using DelimitedFiles

# ============================================================
#  Test: Compare Rin (transmission-normalized) with Mathematica Teukolsky package
#
#  Reference values generated by generate_Rin_reference.wls
#  using TeukolskyRadial[s,l,m,a,ω, Method->"MST", BoundaryConditions->"In"]
#  which divides the MST series by InTrans (= our Btrans), so that
#  Rin is normalized to unit transmission coefficient at the horizon.
#
#  Julia: Rin_normalized = Rin(p, ν, fn, r) / Btrans
#
#  where Btrans is computed with the Wolfram-compatible InTrans formula:
#    InTrans = 4^s κ^{2s} exp(i(ε+τ)κ(1/2 + logκ/(1+κ))) * Σfn
# ============================================================

"""
Compute InTrans using the Wolfram Teukolsky package convention (MST.m line 106):
  InTrans = 4^s κ^{2s} exp(i(ε+τ)κ(1/2 + logκ/(1+κ))) * Σfn
"""
function compute_InTrans(p::MSTParams, fn; nmax::Int=80)
    s, ε, τ, κ = p.s, p.ϵ, p.τ, p.κ
    Σfn = sum(get(fn, n, 0.0+0.0im) for n in -nmax:nmax)
    prefac = complex(4.0)^s * κ^(2s) * exp(im * (ε + τ) * κ * (0.5 + log(κ) / (1 + κ)))
    return prefac * Σfn
end

# Load reference data from CSV
csv_path = joinpath(@__DIR__, "Rin_reference.csv")
raw = readdlm(csv_path, ','; skipstart=1)

println("="^80)
println("Rin comparison: Julia (transmission-normalized) vs Mathematica Teukolsky package")
println("="^80)
@printf("%-5s %-3s %-3s %-5s %-20s %-5s | %-12s %-12s | %s\n",
        "s", "l", "m", "a", "ω", "r", "|Rin_julia|", "|Rin_math|", "rel_err")
println("-"^80)

n_pass = 0
n_fail = 0
tol = 1e-6

# CSV columns: s, l, m, a, Re_omega, Im_omega, r, Re_Rin, Im_Rin
for i in 1:size(raw, 1)
    s = Int(raw[i, 1])
    l = Int(raw[i, 2])
    m = Int(raw[i, 3])
    a = raw[i, 4]
    ω = complex(raw[i, 5], raw[i, 6])
    r = raw[i, 7]
    Rin_math = complex(raw[i, 8], raw[i, 9])

    # Compute with our code
    ν, p = compute_nu(s, l, m, a, ω)
    fn = compute_fn(p, ν; nmax=80)

    # Raw Rin (unnormalized)
    Rin_raw = Rin(p, ν, fn, r; nmax=80)

    # Normalize by InTrans (Wolfram convention)
    InTrans = compute_InTrans(p, fn; nmax=80)
    Rin_julia = Rin_raw / InTrans

    rel_err = abs(Rin_julia - Rin_math) / abs(Rin_math)
    status = rel_err < tol ? "PASS" : "FAIL"

    if rel_err < tol
        global n_pass += 1
    else
        global n_fail += 1
    end

    ω_str = imag(ω) == 0 ? @sprintf("%-18.1f", real(ω)) :
            @sprintf("%+.2f%+.2fi", real(ω), imag(ω))
    @printf("%-5d %-3d %-3d %-5.1f %-20s %-5.1f | %12.4e %12.4e | %.2e  [%s]\n",
            s, l, m, a, ω_str, r, abs(Rin_julia), abs(Rin_math), rel_err, status)

    if rel_err >= tol
        @printf("  Julia:       %+.10e %+.10ei\n", real(Rin_julia), imag(Rin_julia))
        @printf("  Mathematica: %+.10e %+.10ei\n", real(Rin_math), imag(Rin_math))
        @printf("  InTrans:     %+.10e %+.10ei\n", real(InTrans), imag(InTrans))
        @printf("  Rin_raw:     %+.10e %+.10ei\n", real(Rin_raw), imag(Rin_raw))
    end
end

println("-"^80)
@printf("Results: %d PASS, %d FAIL out of %d tests (tol = %.0e)\n",
        n_pass, n_fail, size(raw, 1), tol)

# ============================================================
#  Bonus: Check that our Btrans (from compute_amplitudes) agrees with InTrans
# ============================================================
println()
println("="^80)
println("Bonus: Btrans (Julia amplitudes) vs InTrans (Wolfram formula)")
println("="^80)
@printf("%-5s %-3s %-3s %-5s %-20s | %-14s %-14s | %s\n",
        "s", "l", "m", "a", "ω", "|Btrans_julia|", "|InTrans|", "rel_err")
println("-"^80)

for i in 1:size(raw, 1)
    s = Int(raw[i, 1])
    l = Int(raw[i, 2])
    m = Int(raw[i, 3])
    a = raw[i, 4]
    ω = complex(raw[i, 5], raw[i, 6])

    amps = compute_amplitudes(s, l, m, a, ω; nmax=80)
    fn = amps.fn
    p = MSTParams(s, l, m, a, ω)
    ν = amps.ν

    InTrans = compute_InTrans(p, fn; nmax=80)
    Btrans_julia = amps.Btrans

    rel = abs(Btrans_julia - InTrans) / abs(InTrans)
    match = rel < 1e-8 ? "≈" : "≠"

    ω_str = imag(ω) == 0 ? @sprintf("%-18.1f", real(ω)) :
            @sprintf("%+.2f%+.2fi", real(ω), imag(ω))
    @printf("%-5d %-3d %-3d %-5.1f %-20s | %14.6e %14.6e | %.2e  [%s]\n",
            s, l, m, a, ω_str,
            abs(Btrans_julia), abs(InTrans), rel, match)
end
println("-"^80)
