using Pkg
Pkg.activate("/Users/yusuke/work/BHPtoolkit.jl")

using BHPtoolkit
using Printf
using DelimitedFiles

# ============================================================
#  Test: Compare Rup (transmission-normalized) with Mathematica Teukolsky package
#
#  Reference values generated by generate_Rup_reference.wls
#  using TeukolskyRadial[s,l,m,a,ω, Method->"MST", BoundaryConditions->"Up"]
#  which divides the MST series by UpTrans (= our Ctrans), so that:
#    Rup ~ r^{-1-2s} e^{+iωr*}  at infinity.
# ============================================================

# Load reference data from CSV
csv_path = joinpath(@__DIR__, "Rup_reference.csv")
raw = readdlm(csv_path, ','; skipstart=1)
ref = raw

println("="^80)
println("Rup comparison: Julia (transmission-normalized) vs Mathematica Teukolsky package")
println("="^80)
@printf("%-5s %-3s %-3s %-5s %-12s %-5s | %-12s %-12s | %s\n",
        "s", "l", "m", "a", "ω", "r", "|Rup_julia|", "|Rup_math|", "rel_err")
println("-"^80)

n_pass = 0
n_fail = 0
tol = 1e-6

# CSV columns: s, l, m, a, Re_omega, Im_omega, r, Re_Rup, Im_Rup
for i in 1:size(ref, 1)
    s = Int(ref[i, 1])
    l = Int(ref[i, 2])
    m = Int(ref[i, 3])
    a = ref[i, 4]
    ω = complex(ref[i, 5], ref[i, 6])
    r = ref[i, 7]
    Rup_math = complex(ref[i, 8], ref[i, 9])

    # Compute with our code
    ν, p = compute_nu(s, l, m, a, ω)
    fn = compute_fn(p, ν; nmax=80)
    Rup_julia = Rup(p, ν, fn, r; nmax=80)

    rel_err = abs(Rup_julia - Rup_math) / abs(Rup_math)
    status = rel_err < tol ? "PASS" : "FAIL"

    if rel_err < tol
        global n_pass += 1
    else
        global n_fail += 1
    end

    ω_str = imag(ω) == 0 ? @sprintf("%-10.1f", real(ω)) :
            @sprintf("%+.1f%+.1fi", real(ω), imag(ω))
    @printf("%-5d %-3d %-3d %-5.1f %-12s %-5.1f | %12.4e %12.4e | %.2e  [%s]\n",
            s, l, m, a, ω_str, r, abs(Rup_julia), abs(Rup_math), rel_err, status)

    if rel_err >= tol
        @printf("  Julia:       %+.10e %+.10ei\n", real(Rup_julia), imag(Rup_julia))
        @printf("  Mathematica: %+.10e %+.10ei\n", real(Rup_math), imag(Rup_math))
    end
end

println("-"^80)
@printf("Results: %d PASS, %d FAIL out of %d tests (tol = %.0e)\n",
        n_pass, n_fail, size(ref, 1), tol)
